# Use root/example as user/password credentials
version: "3.6"

networks:
    cibertec/development: {}
services:
    mongo:
        image: mongo:latest
        container_name: mongo_emisionvotos
        hostname: mongo_emisionvotos
        labels:
            edu.cibertec.votoelectronico.project: "EmisionVotos"
            edu.cibertec.votoelectronico.version: "1.0"
            edu.cibertec.votoelectronico.author.name: "Christian Rivera"
            edu.cibertec.votoelectronico.author.email: "crivera2093@gmail.com"
            edu.cibertec.votoelectronico.author.url: "https://github.com/pSharpX"
            edu.cibertec.votoelectronico.author.description: "EmisionVotos Application"
        networks:
            - cibertec/development
        ports:
            - "27018:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: $$admin123.a
            MONGO_INITDB_DATABASE: admin
        volumes:
            - ./data/mongo-scripts/:/docker-entrypoint-initdb.d/
        command: ["--auth"]
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: wildfly_emisionvotos
        hostname: wildfly_emisionvotos
        labels:
            edu.cibertec.votoelectronico.project: "EmisionVotos"
            edu.cibertec.votoelectronico.version: "1.0"
            edu.cibertec.votoelectronico.author.name: "Christian Rivera"
            edu.cibertec.votoelectronico.author.email: "crivera2093@gmail.com"
            edu.cibertec.votoelectronico.author.url: "https://github.com/pSharpX"
            edu.cibertec.votoelectronico.author.description: "EmisionVotos Application"
        networks:
            - cibertec/development
        ports:
            - "8080:8080"
            - "9990:9990"
        restart: always
        volumes:
            - ./data/app/log:/opt/jboss/wildfly/standalone/log
        command:
            [
                "/opt/jboss/wildfly/bin/standalone.sh",
                "-b",
                "0.0.0.0",
                "-bmanagement",
                "0.0.0.0",
            ]
        depends_on:
            - mongo
    client:
        build:
            context: ./
            dockerfile: Dockerfile.client
        container_name: javaclient_emisionvotos
        hostname: javaclient_emisionvotos
        labels:
            edu.cibertec.votoelectronico.project: "EmisionVotos"
            edu.cibertec.votoelectronico.version: "1.0"
            edu.cibertec.votoelectronico.author.name: "Christian Rivera"
            edu.cibertec.votoelectronico.author.email: "crivera2093@gmail.com"
            edu.cibertec.votoelectronico.author.url: "https://github.com/pSharpX"
            edu.cibertec.votoelectronico.author.description: "EmisionVotos Application"
        networks:
            - cibertec/development
        restart: always
        environment:
            - JAVA_OPTS
        volumes:
            - ./data/app/tmp:/tmp
        entrypoint:
            [
                "./wait-for-it.sh",
                "web:8080",
                "--",
                "sh",
                "-c",
                "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /EmisionVoto_Client-1.0-SNAPSHOT.jar",
            ]
        depends_on:
            - web
