FROM centos

# install java8 jdk
RUN yum update -y && \
yum install -y wget && \
yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel && \
yum clean all

VOLUME /tmp
ADD rents-v1-SNAPSHOT-v1-SNAPSHOT.jar /rents-v1-SNAPSHOT-v1-SNAPSHOT.jar
RUN sh -c 'touch /rents-v1-SNAPSHOT-v1-SNAPSHOT.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar -Dspring.profiles.active=default /rents-v1-SNAPSHOT-v1-SNAPSHOT.jar" ]