version: "3.6"

networks:
    graphbook/in.production: {}
    graphbook/production: {}

secrets:
    db_user:
        file: ./secrets/db_user
    db_password:
        file: ./secrets/db_password
    db_root_password:
        file: ./secrets/db_root_password

services:
    database:
        image: mariadb:latest
        container_name: database_graphbook
        hostname: ${DATABASE_HOSTNAME}
        secrets:
            - db_user
            - db_password
            - db_root_password
        labels:
            edu.cibertec.graphbook.project: "GraphBook"
            edu.cibertec.graphbook.version: "1.0"
            edu.cibertec.graphbook.author.name: "Christian Rivera"
            edu.cibertec.graphbook.author.email: "crivera2093@gmail.com"
            edu.cibertec.graphbook.author.url: "https://github.com/pSharpX"
            edu.cibertec.graphbook.author.description: "GraphBook Application"
        networks:
            - graphbook/in.production
        ports:
            - "3306:3306"
        restart: always
        environment:
            MARIADB_USER_FILE: /run/secrets/db_user
            MARIADB_PASSWORD_FILE: /run/secrets/db_password
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MARIADB_DATABASE: ${DATABASE_NAME}
        volumes:
            - ./data/db-scripts/:/docker-entrypoint-initdb.d/
            - ./data/db/:/var/lib/mysql
    api:
        build:
            context: ./
            dockerfile: Dockerfile
        image: psharpx/graphbook-api:${TAG}
        container_name: api_graphbook
        hostname: api.graphbook.pe
        secrets:
            - db_user
            - db_password
        labels:
            edu.cibertec.graphbook.project: "GraphBook"
            edu.cibertec.graphbook.version: "1.0"
            edu.cibertec.graphbook.author.name: "Christian Rivera"
            edu.cibertec.graphbook.author.email: "crivera2093@gmail.com"
            edu.cibertec.graphbook.author.url: "https://github.com/pSharpX"
            edu.cibertec.graphbook.author.description: "GraphBook Application"
        networks:
            - graphbook/in.production
        restart: always
        environment:
            HOST: ${DATABASE_HOSTNAME}
            DATABASE: ${DATABASE_NAME}
            USERNAME: "{{DOCKER-SECRET:db_user}}"
            PASSWORD: "{{DOCKER-SECRET:db_password}}"
        depends_on:
            - database
    server:
        image: nginx:1.21.3-alpine
        container_name: integration_graphbook
        hostname: integration.graphbook.pe
        labels:
            edu.cibertec.graphbook.project: "GraphBook"
            edu.cibertec.graphbook.version: "1.0"
            edu.cibertec.graphbook.author.name: "Christian Rivera"
            edu.cibertec.graphbook.author.email: "crivera2093@gmail.com"
            edu.cibertec.graphbook.author.url: "https://github.com/pSharpX"
            edu.cibertec.graphbook.author.description: "GraphBook Application"
        networks:
            - graphbook/in.production
            - graphbook/production
        volumes:
            - ./config/vhost_server.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - api
    web:
        build:
            context: ./
            dockerfile: Dockerfile.client
            args:
                SOME_ARGS: some_args
        image: psharpx/graphbook-web:${TAG}
        container_name: web_graphbook
        hostname: web.graphbook.pe
        labels:
            edu.cibertec.graphbook.project: "GraphBook"
            edu.cibertec.graphbook.version: "1.0"
            edu.cibertec.graphbook.author.name: "Christian Rivera"
            edu.cibertec.graphbook.author.email: "crivera2093@gmail.com"
            edu.cibertec.graphbook.author.url: "https://github.com/pSharpX"
            edu.cibertec.graphbook.author.description: "GraphBook Application"
        networks:
            - graphbook/production
        restart: always
        ports:
            - "8081:80"
        depends_on:
            - server
